stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: alexfengcisco/alex_os:v01
      registry: index.docker.io
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
