apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-alexnamespace01-alexpipeline
  name: alexpipeline
  namespace: alexnamespace01
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-alexnamespace01-alexpipeline
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-alexnamespace01-alexpipeline
    spec:
      containers:
      - image: alexfengcisco/alex_os:v01
        imagePullPolicy: Always
        name: alexpipeline
        ports:
        - containerPort: 8000
          name: 8000tcp02
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: alexpipeline
  namespace: alexnamespace01
spec:
  clusterIP: None
  ports:
  - name: default
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    workload.user.cattle.io/workloadselector: deployment-alexnamespace01-alexpipeline
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alexpipeline
  namespace: alexnamespace01
spec:
  rules:
  - host: alexpipeline.alexnamespace01.10.75.58.92.xip.io
    http:
      paths:
      - backend:
          serviceName: alexpipeline
          servicePort: 8000

