apiVersion: apps/v1
kind: Deployment
  name: alexospipeline
  namespace: alexnamespace01
spec:
  containers:
  - image: alexfengcisco/alexpipeline01
    name: alexospipeline
  imagePullSecrets:
  - name: dockerhub
